<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Bogus" Version="35.6.3" />
		<PackageReference Include="coverlet.collector" Version="6.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="xunit" Version="2.5.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Modules\ExporterBootstrap\ExporterBootstrap.csproj" />
		<ProjectReference Include="..\Modules\ExporterCommon\ExporterCommon.csproj" />
		<ProjectReference Include="..\Modules\ExporterGameSessions\ExporterGameSessions.csproj" />
		<ProjectReference Include="..\Modules\ExporterLibraryExporter\ExporterLibraryExporter.csproj" />
		<ProjectReference Include="..\Modules\ExporterPlayAtlasClient\ExporterPlayAtlasClient.csproj" />
		<ProjectReference Include="..\Modules\ExporterPlayniteIntegration\ExporterPlayniteIntegration.csproj" />
		<ProjectReference Include="..\Modules\ExporterSystem\ExporterSystem.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Playnite.SDK, Version=6.12.0.0, Culture=neutral, processorArchitecture=MSIL">
			<HintPath>..\packages\PlayniteSDK.6.12.0\lib\net462\Playnite.SDK.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

</Project>
